--[[--
UI Dialogs and Viewers for Gemini AI Book Illustrator.
Renders scene suggestion lists, full-screen image views, and custom page range pickers.
--]]--

local _ = require("gettext")
local ButtonDialog = require("ui/widget/buttondialog")
local ImageViewer = require("ui/widget/imageviewer")
local InfoMessage = require("ui/widget/infomessage")
local InputDialog = require("ui/widget/inputdialog")
local Menu = require("ui/widget/menu")
local UIManager = require("ui/uimanager")

local SceneDialog = {}
SceneDialog.__index = SceneDialog

function SceneDialog:new(settings)
    local self = setmetatable({}, SceneDialog)
    self.settings = settings
    return self
end

-- Show list of AI-suggested scenes from chapter analysis
function SceneDialog:showScenePicker(scenes, chapter_title, on_select_callback)
    local menu_items = {}

    for idx, scene in ipairs(scenes) do
        local title = scene.title or string.format(_("Scene #%d"), idx)
        local summary = scene.summary or ""
        local quote = scene.quote and (#scene.quote > 0) and string.format('"%s"', scene.quote) or ""
        local help = (#quote > 0) and quote or summary

        table.insert(menu_items, {
            text = string.format("✨ %s", title),
            help_text = help,
            callback = function()
                if on_select_callback then
                    on_select_callback(scene)
                end
            end,
        })
    end

    table.insert(menu_items, {
        text = _("Cancel"),
        callback = function() end,
    })

    local picker_menu = Menu:new{
        title = string.format(_("AI Scenes: %s"), chapter_title or _("Chapter")),
        item_table = menu_items,
        is_borderless = true,
    }
    UIManager:show(picker_menu)
end

-- Show Fullscreen Image Viewer with Quick Action Buttons
function SceneDialog:showGeneratedArtwork(image_path, scene_info, book_info)
    if not image_path then return end

    local title = (scene_info and scene_info.title) or "AI Illustration"
    local scene_prompt = (scene_info and scene_info.visual_prompt) or ""

    -- 1. Open ImageViewer
    local viewer = ImageViewer:new{
        file = image_path,
        with_title = true,
        title = title,
    }
    UIManager:show(viewer)

    -- 2. Offer action dialog overlay (Save as Screensaver, Set as Cover, Done)
    local dialog
    dialog = ButtonDialog:new{
        title = title,
        text = (scene_info and scene_info.summary) or _("Illustration generated by Google Gemini."),
        buttons = {
            {
                {
                    text = _("🖼️ Set as Screensaver"),
                    callback = function()
                        UIManager:close(dialog)
                        local ok_sc, msg = self:saveAsScreensaver(image_path)
                        UIManager:show(InfoMessage:new{
                            text = msg,
                            timeout = 2.5,
                        })
                    end,
                },
                {
                    text = _("📖 Set as Book Cover"),
                    callback = function()
                        UIManager:close(dialog)
                        local ok_cov, msg = self:saveAsCover(image_path, book_info)
                        UIManager:show(InfoMessage:new{
                            text = msg,
                            timeout = 2.5,
                        })
                    end,
                },
                {
                    text = _("Dismiss"),
                    callback = function()
                        UIManager:close(dialog)
                    end,
                },
            },
        },
    }
    -- Show overlay action options after image loads
    UIManager:scheduleIn(0.5, function()
        UIManager:show(dialog)
    end)
end

-- Copy image to Kindle screensavers directory
function SceneDialog:saveAsScreensaver(image_path)
    local target_dirs = {
        "/mnt/us/screensavers",
        "/mnt/us/koreader/screensavers",
        "/mnt/us/koreader/settings/screensavers",
    }

    local target_file = nil
    for _, dir in ipairs(target_dirs) do
        pcall(function() os.execute(string.format('mkdir -p "%s"', dir)) end)
        local f = io.open(dir .. "/test.tmp", "w")
        if f then
            f:close()
            os.remove(dir .. "/test.tmp")
            target_file = string.format("%s/gemini_art_%d.png", dir, os.time())
            break
        end
    end

    if not target_file then
        target_file = "/mnt/us/screensaver.png"
    end

    local copy_cmd = string.format('cp "%s" "%s"', image_path, target_file)
    os.execute(copy_cmd)
    return true, string.format(_("Saved to Screensavers!\n(%s)"), target_file)
end

-- Save image as book cover
function SceneDialog:saveAsCover(image_path, book_info)
    local target_dir = "/mnt/us/koreader/bookart/covers"
    pcall(function() os.execute(string.format('mkdir -p "%s"', target_dir)) end)

    local safe_title = (book_info and book_info.title or "cover"):gsub("[^%w_%-]", "_")
    local target_file = string.format("%s/%s_cover.png", target_dir, safe_title)

    local copy_cmd = string.format('cp "%s" "%s"', image_path, target_file)
    os.execute(copy_cmd)
    return true, string.format(_("Saved as Book Cover!\n(%s)"), target_file)
end

-- Show input dialog for custom page range (e.g. "12-24")
function SceneDialog:showPageRangeDialog(cur_page, on_confirm_callback)
    local dialog
    dialog = InputDialog:new{
        title = _("Scan Custom Page Range"),
        description = _("Enter page range to analyze (e.g. 15-28 or 10):"),
        input = string.format("%d-%d", math.max(1, cur_page - 2), cur_page + 8),
        buttons = {
            {
                {
                    text = _("Cancel"),
                    id = "close",
                    callback = function() UIManager:close(dialog) end,
                },
                {
                    text = _("Analyze with Gemini"),
                    is_enter_default = true,
                    callback = function()
                        local input_str = dialog:getInputText()
                        UIManager:close(dialog)

                        local s_p, e_p = input_str:match("(%d+)%s*-%s*(%d+)")
                        if not s_p then
                            s_p = input_str:match("(%d+)")
                            e_p = s_p
                        end

                        s_p = tonumber(s_p) or cur_page
                        e_p = tonumber(e_p) or (s_p + 10)

                        if on_confirm_callback then
                            on_confirm_callback(s_p, e_p)
                        end
                    end,
                },
            },
        },
    }
    UIManager:show(dialog)
    dialog:onShowKeyboard()
end

return SceneDialog
